@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.progression.recipes;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
