@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.progression.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
